### ISSUE TITLE
dodanie mapowania skróconych nazw ulic w PRG

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/gugik2osm#1]

**Comment by szydzio** [comment]
Hej Tomasz!
Czy ten plik z ulicami które powinny się automatycznie korygować z PRG jest jeszcze gdzieś dostępna?
Na forum pojawił się użytkownik, który [chciałby korygować](https://forum.openstreetmap.org/viewtopic.php?pid=817550#p817550) w JOSM "M. Kopernika" do "Mikołaja Kopernika", zastanawiam się czy nie dałoby się tego automatycznie skorygować tuż po zaciągnięciu danych z PRG?
Pozdr!

**Comment by ttomasz** [comment]
Hej, trochę zmienialiśmy strukturę tego pliku/tabeli, żeby robić to na bardziej szczegółowym poziomie, bo nie zawsze mapowanie jest takie samo w różnych miejscowościach. @mskakuj się tym zajmował, ale najpierw jeszcze wyszło, że było parę błędów w moich skryptach weryfikujących zawartość PRG i w samym PRG i kolega najpierw to poprawiał. Ogólnie będziemy chcieli te mapowania zrobić, żeby nie trzeba było potem poprawiać tych nazw po importach jeżeli ktoś zapomni tego zweryfikować.

**Comment by mskakuj** [comment]
finalizuję prace nad plikiem mapującym. Najpóźniej do końca tego tygodnia plik będzie dostępny. Będzie w nim ponad 9000 mapowań. M. Kopernika także.

**Comment by ttomasz** [comment]
aktualizacja danych zakończona, 99,99% powinno już mieć skróty rozwinięte
![image](https://user-images.githubusercontent.com/31594210/107154877-8ba70100-6975-11eb-9553-04ee9f7176bc.png)
![image](https://user-images.githubusercontent.com/31594210/107154885-93ff3c00-6975-11eb-990a-87e933432b65.png)

**Comment by szydzio** [comment]
Super! 
To z pewnościa pomoże ograniczyć "mrówki" po importach.
Dzięki! :)
