### ISSUE TITLE
Budynki znikły

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/gugik2osm#104]
przekazuje i potwierdzam

> Od paru dni na stronie "budynki.openstreetmap.org.pl" nie wyświetlają się budynki niezmapowane w OSM. Pokazywały się one na mapie w kolorze czerwonym. W opcjach mam zaznaczoną opcję wyświetlania warstwy "budynki". Warstwa "adresy" wyświetla się prawidłowo. Czy ta opcja pokazywania budynków została wyłączona?

**Comment by ttomasz** [comment]
Hej, dzięki za info. Na razie nie mam czasu nic z tym zrobić, więc plan jest poczekać do piątku/soboty na reload i może się samo naprawi.
