### ISSUE TITLE
Błędny numer miesiąca dla zestawu zmian

### ISSUE THREAD

**Issue by maraf24** [openstreetmap-polska/gugik2osm#116]
Numer miesiąca jest o 1 za mały, jak widać na obrazku - jest 10, powinno być 11
![image](https://user-images.githubusercontent.com/10471006/201472446-addc646b-82af-4088-b99b-fcc9934d90bd.png)

Zestaw z obrazka:
https://www.openstreetmap.org/changeset/128807830

**Comment by ttomasz** [comment]
#138

**Comment by polish96** [comment]
#145
