### ISSUE TITLE
Propozycja zmiany klucza source dla budynków

### ISSUE THREAD

**Issue by maraf24** [openstreetmap-polska/gugik2osm#126]
W tej chwili każdy importowany budynek ma dodawany tag 
`source=www.geoportal.gov.pl`

Jest tym samym bardzo niekonkretny, gdyż:
1. source jest ogólne, w przypadku np. dodania poi do budynku przestaje być jasne, czego ono dotyczy (budynku czy poi)
2. www.geoportal.gov.pl jest bardzo ogólne, na tym portalu jest przecież dostępna także inna baza budynków (Integracja), a import nie pochodzi z niej

Proponowałbym zmianę na bardziej szczegółowy tag, np.
`source:building=BDOT`

**Comment by Zaczero** [comment]
Podbijam wątek, nowe budynki mogłyby mieć dodawany sam <kbd>source:building</kbd> a przeszukiwanie bazy mogło by być hybrydowe, tak aby zmiana była kompatybilna wstecznie. Oznaczę jako bug, bo oznaczenie <kbd>source=www.geoportal.gov.pl</kbd> wygląda bardziej na błąd.

**Comment by ttomasz** [comment]
Zmienione w 6d27b69fd9d2e93f2fa6f4227ba7e805017654b0
