### ISSUE TITLE
Internal server error przy pobieraniu

### ISSUE THREAD

**Issue by kuba-orlik** [openstreetmap-polska/gugik2osm#13]
Chciałem skorzystać z apki i wywaliło mi błąd kiedy spróbowałem pobrać adresy:

>Internal Server Error
>
>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

URL: https://budynki.openstreetmap.org.pl/prg/not_in/osm/?format=osm&filter_by=bbox&xmin=16.863585371170046&ymin=52.39068878668775&xmax=16.898022730103435&ymax=52.40093300574995

Pobieranie budynków raz mi zadziałało, a potem także rzuciło errorem :<

PS Super pomysł na projekt!

**Comment by ttomasz** [comment]
@kuba-orlik dzięki za zgłoszenie, zrestartowałem service, bo transakcja się zablokowała, teraz powinno działać. Muszę dodać wyłapywanie takich wyjątków, żeby serwer sam był w stanie sobie z takimi sytuacjami poradzić :)

**Comment by ttomasz** [comment]
Dodałem poprawkę, która powinna pomóc na przyszłość, ale ciężko to przetestować, więc na razie zamykam issue.

**Comment by kuba-orlik** [comment]
Dzieki! Jak by sie blad powtorzyl to zglosze ponownie ;)
