### ISSUE TITLE
padł serwer

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#152]
Widzę ogłoszenie, że błędy nie będą poprawiane, ale niedziałający serwer chyba nie jest z tym związany?

```
502 Bad Gateway

nginx/1.18.0 (Ubuntu)
```

**Comment by polish96** [comment]
> Widzę ogłoszenie, że błędy nie będą poprawiane, ale niedziałający serwer chyba nie jest z tym związany?
> 
> ```
> 502 Bad Gateway
> 
> nginx/1.18.0 (Ubuntu)
> ```

Na Discordzie trwają rozmowy m.in. @kocio-pl i @Zaczero na temat przywrócenia serwera do działania.

**Comment by Zaczero** [comment]
W sumie skraca się to do tego że dysk z danymi wydał z siebie ostatnie tchnienie. Ja próbowałem coś przywrócić z kopii zapasowej w nietypowym formacie (nie miała to być kopia zapasowa) ale mi się nie udało. Teraz ma do tego przysiąść kocio. Jeśli jemu także się nie uda to postawimy usługę od zera.

**Comment by maro-21** [comment]
Strona już jest, ale brak adresów.

**Comment by polish96** [comment]
Strona już działa. Brakujące adresy i budynki już się wyświetlają.

**Comment by maro-21** [comment]
A zgłoszonych adresów nie dało się odzyskać? Czy teraz trzeba je jeszcze raz wyklikać?

**Comment by Zaczero** [comment]
Z tym czekamy na @kocio-pl - jest szansa, że może jemu uda się coś odzyskać. Usługa została teraz postawiona od zera, aby była i nie trzeba było dłużej stopować pracy. Lepsze to niż kompletnie niedziałająca strona.
