### ISSUE TITLE
Różnice między adresami z e-mapa.net a PRG

### ISSUE THREAD

**Issue by maraf24** [openstreetmap-polska/gugik2osm#18]
Gminy korzystające z usług Geo-systemu - https://www.punktyadresowe.pl/ - aktualne adresy mają w tym systemie.
Często występują różnice między nimi a adresami z PRG, niestety na niekorzyść PRG. 
Adresy dla tych gmin można pobrać z https://integracja.gugik.gov.pl/daneadresowe/
Czy to nie jest to samo źródło co PRG?
Jak można zapobiec importom takich nieaktualnych adresów?

**Comment by ttomasz** [comment]
Gminy prowadzą rejestr adresów (EMUiA), niektóre z nich prowadzą ten rejestr używając oprogramowania Geo-System: IMPA. Gminy potem wysyłają aktualizacje do GUGiK do PRG. 

Generalnie Geo-System z tego co wiem ma automatyczne wysyłanie danych do PRG, więc dla gmin które z nich korzystają (to co ma url e-mapa na podanej stronie integracji, reszta to inne systemy) powinno to trafiać do PRG regularnie i nie powinno być opóźnień większych niż kilka tygodni. Nie wiem jak często oni wysyłają aktualizacje do PRG, część gmin robi to miesięcznie. Ja pobieram PRG co tydzień ze strony GUGiK.

**Comment by ttomasz** [comment]
EMUiA to jednocześnie nazwa programu udostępnianego przez GUGiK za darmo dla gmin i samego rejestru adresowego gminnego.

**Comment by ttomasz** [comment]
Ciężko powiedzieć jak temu zapobiec, mógłbym teoretycznie ciągnąć dla części gmin CSV od geosystemu z tej strony z integracją, ale myślę, że musiałbym najpierw zrobić lepszy scheduling zadań np w oparciu o Airflow, bo obecnie to są skrypty odpalane przez CRON i jak coś by się źle zadziało to ciężko by to było wychwycić, a im więcej źródeł tym łatwiej, że coś się popsuje :)

**Comment by maraf24** [comment]
Podrzucam przykład: https://www.openstreetmap.org/#map=18/51.18865/22.03122
![Screenshot at 18-44-03](https://user-images.githubusercontent.com/10471006/105785785-09cdd580-5f7c-11eb-9b1d-14178e32a2cf.png)
![photo_2021-01-26_02-07-54](https://user-images.githubusercontent.com/10471006/105785804-16522e00-5f7c-11eb-9580-8e7b60b18214.jpg)

Jak widać zaimportowane zostały adresy, których na e-mapa.net nie ma.
Może te aktualizacje dla GUGIKu z gmin nie zawierają informacji o usunięciu adresów?

**Comment by maraf24** [comment]
Patrzę teraz, a to stary import:) Zmyliło mnie świeże zedytowanie terenu i wrzucenie przypadku na Telegrama.
Jest to wiec przykład na coś innego - że gminy robią weryfikację i usuwają zbędne adresy, lepiej więc adresów na polach  i lasach nie importować.

Poszukam i wrzucę inny przykład - w Zamościu natknąłem się na dużo różnic między PRG i e-mapa.net

**Comment by maraf24** [comment]
Zamość. Adresy w OSM są tym z e-mapa.net i są prawidłowe. PRG ma dodatkowe.
https://mzamosc.e-mapa.net?userview=71
https://budynki.openstreetmap.org.pl/#10.99/51.1106/17.0879&map=18.87/50.7288038/23.2472428

To są zawsze taki same przypadki - budynek przylegające do 2 ulic mają po jednym adresie dla każdej z nich, mimo że w użyciu jest tylko jeden adres. Jest też wersja 3 ulicowa z 3 adresami. Dawno temu przepisy nakazywały tak nadawać adresy.

Ku mojemu zaskoczeniu na https://integracja.gugik.gov.pl/daneadresowe jako portal adresowy prezentujący adresy wcale nie jest podany mzamosc.e-mapa.net, ale mapy.geoportal.gov.pl/imap. I tam są adresy widoczne w PRG.
Wygląda więc na to, że różnice wynikają z tego, że mzamosc.e-mapa.net nie jest źródłem danych.

Jedynym sensownym wytłumaczeniem jest to, że Zamość wcale nie używa e-mapa.net do prowadzania rejestru adresów.
Spotkałem się już kiedyś z taką sytuacją w Pasymiu - https://pasym.e-mapa.net jest od dłuższego czasu nieaktualizowane, gdyż miasto już z tego systemu nie korzysta.

Wszystko wydaje się to potwierdzać - nowe budynki w Zamościu mają adresy w PRG, a nie ma ich na e-mapa.net.
Natomiast na liście ostatnio dodanych adresów i ulic w Zamościu ostatnie wpisy są z 2017 roku.
Jest tu ciekawa sytuacja:
- na e-mapa.net są odsiane stare adresy ale brak nowych
- w PRG są stare nieużywane adresu ale są też nowe

To wyjaśnia "Różnice między adresami z e-mapa.net a PRG". Przynajmniej w części.
Teraz poszukam różnic w gminie, która na pewno korzysta z e-mapa.net :)

**Comment by ttomasz** [comment]
https://mapy.geoportal.gov.pl/imap/Imgp_2.html?locale=pl&gui=new&sessionID=5431126 w PRG są te stare adresy, trzeba napisać do miasta Zamość z pytaniem o to

od razu można ich zapytać kiedy była ostatnia aktualizacja wysyłana przez nich do PRG i jak często to robią

**Comment by ttomasz** [comment]
w sumie w tym wątku chyba nie ma nic do dodania, więc zamykam
