### ISSUE TITLE
adresy blisko siebie

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/gugik2osm#19]
komentarz maro-21
Te 2 metry to nie jest tak naprawdę rzeczywista odległość, a na pewno nie zawsze, jeśli aplikacja działa tak jak pisałeś wcześniej, że w przypadku adresu na budynku bierze odległość od jego środka ciężkości. Czasami adresy mogą być dodane przez kogoś ręcznie i wtedy punkt nie będzie dokładnie w tym samym miejscu co w PRG. Pewnie w rzeczywistości adresy reprezentujące wejścia do klatki budynku nie będą w odległości mniejszej niż 1,5 m, bo tyle to szerokość drzwi. Piszę to dlatego, że spokojnie można zmniejszyć nawet do jednego metra:)

![image](https://user-images.githubusercontent.com/31594210/105427277-0faa7a80-5c4d-11eb-91e9-4bb63afa9e82.png)

**Comment by polish96** [comment]
#148
