### ISSUE TITLE
Usuwanie adresów z PRG zweryfikowanych jako nienadające się do importu.

### ISSUE THREAD

**Issue by maraf24** [openstreetmap-polska/gugik2osm#20]
Niektóre adresy widoczne na mapie jako brakujące w osm nie nadają się do zaimportowania.
Przyczyny są różne:
1. inna forma zapisu: w PRG jest 4/6 a w OSM ten adres już jest jako 4-6
2. zgrupowania adresów: w PRG są  3 adresy 6,8,10, w OSM jest jeden 6-10 - i ta forma jest używana w rzeczywistości
3. adres w OSM już jest, tylko w znacznej odległości od tego w PRG (to jest chyba 150m?)
4. adres widoczny w PRG w realu już nie istnieje - tu przyczyny są różne: albo ta zmiana jeszcze nie trafiła do PRG albo jest błąd w danych lokalnych, który został wykryty po weryfikacji w terenie

Przydałby się sposób oznaczenia takich adresów nienadających się do zaimportowania do OSM, by nie było ich widać jako brakujących w OSM, bo teraz niestety zdarza się, mapujący wrzuca do OSM takie duplikaty czy niedawno usunięte adresy.

**Comment by ttomasz** [comment]
Dobry pomysł. 
Problem dotyczy nie tylko adresów, ale i budynków. Widziałem w Warszawie kilka, które zostały wyburzone, a pokazuje jako "brakujące", jako że dane o budynkach 3D nie są aktualizowane.

Dodam do tooltipa z informacją o adresie guzik do zgłaszania takich przypadków, co by je wykluczało z pokazywania. Dodam też tooltipa z guzikiem dla budynków.
Zobaczę też czy jest w bibliotece MapBoxa które renderuje mapę narzędzie do zaznaczania wielu obiektów.

**Comment by ttomasz** [comment]
Dodałem przyciski do zgłaszania takich adresów i budynków. Po kliknięciu przycisku jak serwer potwierdzi przyjęcie wyświetli się komunikat potwierdzający.
![image](https://user-images.githubusercontent.com/31594210/83941958-bc83d480-a7ef-11ea-95ad-b29a4df88a74.png)

**Comment by olo81** [comment]
Dla budynków pomocny by był podkład orto do wyboru :) Fajna opcja

**Comment by ttomasz** [comment]
Dodałem zgłaszanie przez narysowanie poligonu.

Na pytanie o podkład orto utworzyłem osobny issue.

**Comment by maro-21** [comment]
Wyjątkowo zgadzam się z marafem. Może wtedy będzie rzadziej cofał moje edycje :)

> bo teraz niestety zdarza się, mapujący wrzuca do OSM takie duplikaty czy niedawno usunięte adresy

Tak, to o mnie mowa :)

> inna forma zapisu: w PRG jest 4/6 a w OSM ten adres już jest jako 4-6

Myślę, że aplikacja powinna takie różnice ignorować i uznawać, że ten adres tam już jest.


Fajnie, że udało się to dodać! Oszczędzi to trochę czasu na oglądaniu tych samych wyburzonych budynków i będzie można się skupić na brakujących.
