### ISSUE TITLE
Dodanie opcji pobierania samych punktów adresowych 

### ISSUE THREAD

**Issue by olo81** [openstreetmap-polska/gugik2osm#21]
Przydała by się opcja samych punktów adresowych, w miastach jak się dodaje brakujące punkty często jest dużo wyburzonych budynków które często lecą razem z importem, weryfikowanie tego to żmudny proces.

**Comment by olo81** [comment]
kurde co zrobił translator :D

**Comment by ttomasz** [comment]
Dodałem rozwijane menu z guzikami pozwalającymi pobrać albo tylko adresy albo tylko budynki.
![image](https://user-images.githubusercontent.com/31594210/84707723-84069800-af5f-11ea-90f4-ce1c24319102.png)
