### ISSUE TITLE
Co się stało ze zgłoszeniami?

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#24]
Czemu stare repozytorium zostało usunięte i nowe stworzone "ręcznie"? Teraz nie mogę śledzić postępów moich zgłoszonych problemów, nie będę mógł też odpowiedzieć na ewentualne pytanie. Przecież można przenieść repo z zachowaniem historii.

**Comment by ttomasz** [comment]
Niestety koledze się omsknął palec i usunął poprzednie repo, a możliwości przywracania usuniętego repo na github są mocno ograniczone. W związku z tym odtworzyłem co się dało tutaj.

**Comment by jendrusk** [comment]
Hm... Za wysokimi uprawnieniami idzie wysoka odpowiedzialność... może trzeba zweryfikować czy wszyscy muszą mieć tak wysokie uprawnienia do tego repozytorium? Nie zakładam złośliwości czy celowości działania... co najwyżej przywołuję dobre praktyki... Sam często proszę żeby mi ktoś zabrał uprawnienia - wtedy nie mam możliwości zepsucia czegoś nieświadomie.

**Comment by ttomasz** [comment]
No osób z takimi uprawnieniami nie ma dużo, tzn jest to praktycznie tylko zarząd stowarzyszenia chyba. No teraz jeszcze ja dostałem żeby zobaczyć czy da się to przywrócić. Więc raczej nie ma o kogo ograniczyć tej listy osób, bo ktoś musi mieć dostęp. Błędy się zdarzają, ale myślę, że taka sytuacja się nie powtórzy :)
