### ISSUE TITLE
Pobieranie adresów tylko z zaznaczenia

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#25]
Zauważyłem, że pojawiła się opcja narysowania wielokąta na mapie.
Jednak działa ona tylko do zgłoszenia nieprawidłowych adresów lub budynków.
Czy planowana jest opcja, aby pobrać dane tylko z zaznaczonego fragmentu? Pozwoliłoby to pobrać tylko fragment jednej miejscowości albo gminy, bez wchodzenia na sąsiednią gminę, powiat lub województwo.

**Comment by ttomasz** [comment]
Dodane
![image](https://user-images.githubusercontent.com/31594210/86053389-ba144380-ba58-11ea-98f0-587a2e33fd61.png)

**Comment by maro-21** [comment]
Dziękuję za szybką reakcję :)
Przyda się ta opcja :)

Hmm. Testuję właśnie, ale ona nie zawsze działa. Chyba jest jakiś limit co do liczby adresów z zaznaczenia.
Jak zaznaczę kilkanaście adresów to jest w porządku, ale jak jest ich dużo, więcej niż 250, to nie pobiera pliku.

**Comment by maro-21** [comment]
Przypuszczam, dlaczego tak jest.
Pod przyciskiem "Pobierz paczkę JOSM" kryje się adres URL, który można skopiować. Mój miał ponad 10 tys. znaków, a limit to 2048.

**Comment by ttomasz** [comment]
No rzeczywiście przewidywałem to raczej na zaznaczenie małej liczby obiektów, a że punkty adresowe mają 36 znakowy id to szybko się limit może wyczerpać. Zmienię request na POST zamiast GET co pozwoli zlikwidować limit.

**Comment by ttomasz** [comment]
Poprawione
