### ISSUE TITLE
zmiana captchy z reCaptcah v2 na v3

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/gugik2osm#27]
w v3 nie trzeba będzie klikać obrazków, automatycznie oceniane jest w skali od 0 do 1 jak prawdopodobne, że akcja zrobiona przez bota (0 to raczej bot 1 to prawie na pewno człowiek)

https://developers.google.com/recaptcha/docs/v3

**Comment by maraf24** [comment]
A może alternatywnie osm'owy OAuth?

**Comment by ttomasz** [comment]
Wolałbym nie chować funkcji zwłaszcza tak prostych za logowaniem.

Jakbym dodawał OAutha to pewnie od razu bym zrobił to żeby była możliwość po prostu klikać obiekty i wysyłać je prosto do OSM. Oryginalnie nawet tak chciałem budynki zaprojektować, ale nie mogłem znaleźć dokumentacji jak to wszystko działa 🤦‍♂️ Nie wiem czy oni to specjalnie chowają, czy to ja nie umiem czytać 🤷‍♂️

**Comment by ttomasz** [comment]
captcha została usunięta
