### ISSUE TITLE
drobne poprawki tekstowe

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#31]
Czy można by zmienić tytuł strony w html z "Strona główna" na coś innego? :) Mając otwarte kilka kart w przeglądarce, zawsze szukam gdzie co jest.

Poza tym można by też przetłumaczyć nazwy przycisków po prawej na polski: Zoom in, Zoom out, itd.

**Comment by ttomasz** [comment]
@maro-21 Mogę zmienić tylko na co? 😃 Gdybym usunął obecny tytuł całkowicie to by wyglądało tak: 
![image](https://user-images.githubusercontent.com/31594210/93719218-5134f700-fb81-11ea-812a-e849faf3cb3a.png)
Nie wiem czy lepiej czy nie? 

Co do nazw przycisków musiałbym zobaczyć czy jest jakaś opcja wybrania języka w bibliotece js mapboxa od mapy, bo jak nie to byłoby ciężko.

**Comment by maro-21** [comment]
> Mogę zmienić tylko na co? Gdybym usunął obecny tytuł całkowicie to by wyglądało tak:

A jak się ta aplikacja nazywa? Gugik2OSM?
Bez tytułu chyba nawet lepiej niż z "Strona głowna" według mnie.

> Co do nazw przycisków musiałbym zobaczyć czy jest jakaś opcja wybrania języka w bibliotece js mapboxa od mapy, bo jak nie to byłoby ciężko.

A, plik ten jest na zewnętrznym serwerze?

**Comment by ttomasz** [comment]
Usunąłem tytuł.

> A jak się ta aplikacja nazywa? Gugik2OSM?

No to jest taka nazwa robocza raczej niż gotowa "marka".

> > Co do nazw przycisków musiałbym zobaczyć czy jest jakaś opcja wybrania języka w bibliotece js mapboxa od mapy, bo jak nie to byłoby ciężko.
> 
> A, plik ten jest na zewnętrznym serwerze?

Tak, ale znalazłem, że chyba jest opcja dodania własnego tłumaczenia przynajmniej do części przycisków. Notatki na przyszłość poniżej:
https://docs.mapbox.com/mapbox-gl-js/api/map/ <- parametr options.locale
Przykładowy plik locale: https://github.com/mapbox/mapbox-gl-js/blob/520a4ca3b9d260693f1e7f4af30d8b91c8f8bb08/src/ui/default_locale.js
Klasa od navigation controls: https://github.com/mapbox/mapbox-gl-js/blob/520a4ca3b9d260693f1e7f4af30d8b91c8f8bb08/src/ui/control/navigation_control.js#L36-L141
