### ISSUE TITLE
Skąd wiemy że importowanie z Państwowego Rejestru Granic jest OK?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/gugik2osm#32]
Obstawiam że zródło to jest OK (brzmi jak jakaś oficjalna baz danych), spore szanse że jest jest dopuszczone korzystanie.

Ale zanim za importowanie się zabiorę chcę mieć 100% pewności.

Czy to jest http://www.gugik.gov.pl/pzgik/dane-bez-oplat/dane-z-panstwowego-rejestru-granic-i-powierzchni-jednostek-podzialow-terytorialnych-kraju-prg ? Bo tam jest tylko że dostępne bez opłat, bez informacji o licencjach.

**Comment by matkoniecz** [comment]
https://budynki.openstreetmap.org.pl/help.html nie zawiera informacji/potwierdzenia że te dane są na licencji kompatybilnej z OSM, nie ma też informacji które pozwalałyby to ustalić.

Nie ma też tego na https://budynki.openstreetmap.org.pl/opis_danych.html

"Dane adresowe z Państwowego Rejestru Granic."

To że coś ma w nazwie "Państwowe" nie oznacza od razu  że można to do OSM importować. W Polsce tak źle teraz chyba nie jest, ale zdarzają się zestawy danych robione przez państwowe instytucje, robione za publiczne pieniądze, udostępniane na kuriozalnych zasadach.

**Comment by ttomasz** [comment]
> Czy to jest http://www.gugik.gov.pl/pzgik/dane-bez-oplat/dane-z-panstwowego-rejestru-granic-i-powierzchni-jednostek-podzialow-terytorialnych-kraju-prg ? Bo tam jest tylko że dostępne bez opłat, bez informacji o licencjach.

Tak to to. Nie mam pod ręką konkretnego zapisu licencji/ustawy, ale dane adresowe są wolne i mogą być importowane, ludzie z forum openstreetmap robią to od lat (niby z zasobów gminnych, ale to te same dane), więc pewnie oni będą ci bardziej szczegółowo opisać stan prawny tego zasobu: https://forum.openstreetmap.org/viewforum.php?id=23

**Comment by matkoniecz** [comment]
> Tak to to.

Czy byłoby OK podlinkowanie tego w https://budynki.openstreetmap.org.pl/opis_danych.html ?

Jak znajdę gdzie to jest modyfikowalne w tym repo to PR bym zrobił.

**Comment by ttomasz** [comment]
Ta podstrona nie odnosi się do danych do importu do OSM tylko o danych GISowych, które można sobie pobrać z serwera w innych celach.

Jak już to informacja odnośnie PRG byłaby do wstawienia do klauzuli informacyjnej na stronie głównej. Tam jest informacja o wykorzystywanych obrysach budynków, który to zbiór już miał licencję wymagającą podania takich informacji.
[Link do lokalizacji w pliku](https://github.com/openstreetmap-polska/gugik2osm/blob/c3ca8ce5ac4a749fbe8c5c437f1015b662bd4ec5/web/index.html#L106)
![image](https://user-images.githubusercontent.com/31594210/98487349-b83a6800-2222-11eb-9d00-22ae7f75a29a.png)

**Comment by matkoniecz** [comment]
Dostałem potwierdzenie, tekst mejla na https://wiki.openstreetmap.org/wiki/Pa%C5%84stwowy_Rejestr_Granic/permission_confirmation

> Dane PRG są elementem państwowego zasobu geodezyjnego i kartograficznego (art. 4 ust. 1a pkt 4 ustawy z dnia 17 maja 1989 r. Prawo geodezyjne i kartograficzne (Dz. U. z 2020 r. poz. 276 z późn. zm.). Zgodnie natomiast z art. 40a ust. 2 pkt 1 lit. a oraz 40c ust. 5 wymienionej ustawy nie pobiera się za te dane opłat i nie wydaje licencji. Tym samym dane PRG mogą być wykorzystywane do dowolnego celu bez ograniczeń.
