### ISSUE TITLE
Co jest dokładnie źródłem adresów?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/gugik2osm#33]
Czy https://dane.gov.pl/pl/dataset/726,panstwowy-rejestr-granic-i-powierzchni-jednostek-podziaow-terytorialnych-kraju/resource/7215/table (by zobaczyć adresy trzeba dać Przejdź do źródła -> powiaty -> gminy itd)

Z kiedy te adresy są? Czy "Dane na dzień: 7 marca 2017" odnosi się aktualności adresów czy czegoś innego?

To dość istotne co do importowania w miejscach gdzie nie mam możliwości weryfikacji adresacji. A gdybym wiedział że dane są aktualne to może i w takich miejscach importy byłyby możliwe.

**Comment by ttomasz** [comment]
Nie korzystałem z zasobów wrzuconych na dane.gov.pl tylko z tego co jest na stronie gugik: http://www.gugik.gov.pl/pzgik/dane-bez-oplat/dane-z-panstwowego-rejestru-granic-i-powierzchni-jednostek-podzialow-terytorialnych-kraju-prg 

Dane na serwer pobieram co tydzień. Do samego PRG dane trafiają z gmin, więc aktualność samych danych zależy jak szybko gminy je do PRG załadują. W danych zdarzają się błędy, bo niektóre gminy je źle zaimportują, albo nie aktualizują ich w PRG w ogóle, ale mimo wszystko PRG to źródło urzędowe i zbierające dane dla całej polski w jednym miejscu.

**Comment by matkoniecz** [comment]
do przetworzenia: https://github.com/openstreetmap-polska/gugik2osm/issues/32#issuecomment-723638125

**Comment by ttomasz** [comment]
> do przetworzenia: [#32 (comment)](https://github.com/openstreetmap-polska/gugik2osm/issues/32#issuecomment-723638125)

Nie do końca rozumiem. Jest jeszcze jakieś pytanie/prośba czy mam zamknąć ten issue?

**Comment by matkoniecz** [comment]
wstawienie do klauzuli informacyjnej na stronie głównej byłoby super

**Comment by ttomasz** [comment]
Dodałem
