### ISSUE TITLE
Poradnik o importowaniu adresów z https://budynki.openstreetmap.org.pl/

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/gugik2osm#34]
Ponieważ sam nie wiedziałem jak to się robi, potanowiłem spisać co się dowiedziałem - by następni mieli łatwiej

Wisi to na https://wiki.openstreetmap.org/wiki/Pl:Importowanie_adres%C3%B3w

Jak ktoś widzić coś co można poprawić - zachęcam do edycji

(wrzucam to tutaj bo może ktoś obserwuje GitHuba a przegapił na forum/telegramie)

**Comment by ttomasz** [comment]
Dodałem link do wiki na głównej stronie na pasku nawigacyjnym, więc w sumie ten issue może zamknę :)

**Comment by matkoniecz** [comment]
Jak jest poprawione to śmiało zamykaj

**Comment by maro-21** [comment]
Ten link ma zły opis i ikonę.
To nie "Wikipedia", tylko "OSM Wiki", albo "Wiki". A ikona też jest Wikipedii.

**Comment by ttomasz** [comment]
Hm no ta ikonka niespecjalnie odróżnia się od tej zwykłej:
![image](https://user-images.githubusercontent.com/31594210/103947561-8d906100-5138-11eb-83e1-f7a3e9d6f5df.png)

**Comment by maro-21** [comment]
To można np.:
Przenieść ikonę do mapy OSM gdzieś indziej, np. na mapę, gdzieś w narożnik.
Albo ikonkę dla Wiki dać coś w stylu ikonki pomocy.
Albo usunąć ją stamtąd i podlinkować ten poradnik tam gdzie jest FAQ/Pomoc, ostanio trochę przybyło tych ikonek i się ciasno tam zrobiło ;)

**Comment by ttomasz** [comment]
Zmieniłem Wikipedię na Wiki. Z tymi ikonkami to nie wiem czy dobrze zmieniać.

**Comment by maro-21** [comment]
To może chociaż zmienić tę ikonkę na inne "W". Bo obecny symbol jest ikonką Wikipedii i się z nią kojarzy ;). A skoro nie ma tam tekstu, jak np. przy "Status", to ikonka powinna być jednoznaczna.

Wyciąłem z logo OSM Wiki taki fragment ;)
![Wiki-logo](https://user-images.githubusercontent.com/57260466/104783602-adea9c00-5786-11eb-96b8-ee872dacc89e.png)

**Comment by ttomasz** [comment]
Mi się OSM Wiki kojarzy z Wikipedią 😅 Szczerze to właściwie nie widzę różnicy za bardzo między jednym, a drugim 🤷‍♂️


![image](https://user-images.githubusercontent.com/31594210/104822422-a1c41480-5842-11eb-902c-35f059cc26cd.png)
Nie wiem czy to dobrze wygląda.
