### ISSUE TITLE
Nie działa cominutowa aktualizacja danych OSM

### ISSUE THREAD

**Issue by CharlesMaZ** [openstreetmap-polska/gugik2osm#35]
Nie działa cominutowa aktualizacja danych OSM. Zatrzymała się 20 listopada o 23:00

**Comment by ttomasz** [comment]
Sprawdzałem teraz i pokazuje, że się aktualizuje. W piątki wieczorem rusza proces aktualizacji cotygodniowej, wtedy aktualizacje minutowe są zatrzymywane, ale dzięki za czujność :)

**Comment by CharlesMaZ** [comment]
Hmmm. W statusie widnieje informacja, że aktualizacja wykonana minutę temu, pozostało 0 kafelków, ale kilka godzin temu zrobiłem import budynków, OSM już wyrenderowało, a na stronie nadal na czerwono i można je pobrać.

**Comment by ttomasz** [comment]
Jaka lokalizacja?

**Comment by CharlesMaZ** [comment]
> Jaka lokalizacja?

https://budynki.openstreetmap.org.pl/#map=13.03/51.49667/22.03002
zrobiłem jeszcze jeden import adresów, w innej lokalizacji gdy aktualizacja już działała i wszystko znikło z budynki.opens...., a tu nadal widnieje

**Comment by ttomasz** [comment]
Hm rzeczywiście coś w tym miejscu się nie zgrało. Spróbuję w tygodniu jeszcze raz zapuścić pełne przeładowanie, bo i tak chcieli na forum żeby zmienić pewne warunki.

**Comment by CharlesMaZ** [comment]
Zauważyłem, ze jak dokonuję zmian w OSM w tym miejscu, to po chwili znikają czerwone budynki na budynki.openstreetmap.org.pl/. 
Widziałem te warunki na forum, ciekawe jak będzie się to sprawować. Nie wiem ile zajęło by czasu dodanie osobnej opcji, aby można było pobrać wszystkie adresy dla danego obszaru. Np. ostatnio spotkałem się z sytuacją, gdzie nadano nowe adresy, i jak był adres np. 5 to teraz taki numer domu jest 100m dalej, ale na budynki.openstreetmap.org.pl/ nie pokazują się te adresy.

**Comment by ttomasz** [comment]
> Nie wiem ile zajęło by czasu dodanie osobnej opcji, aby można było pobrać wszystkie adresy dla danego obszaru. Np. ostatnio spotkałem się z sytuacją, gdzie nadano nowe adresy, i jak był adres np. 5 to teraz taki numer domu jest 100m dalej, ale na budynki.openstreetmap.org.pl/ nie pokazują się te adresy.

Ale co byś chciał wtedy z takimi adresami co się przesunęły o 100m robić? Bo te paczki które generuje strona są w tej chwili tak zrobione, że to będzie wrzucać nowe obiekty do OSM i w OSM wtedy zostałyby i stare i nowe. W sumie nawet nie jestem pewien co mogłoby być przyczyną takiego przesunięcia ze strony gminy. Jaka to lokalizacja?

**Comment by ttomasz** [comment]
Przeładowałem dane i budynki już się nie pojawiają

**Comment by CharlesMaZ** [comment]
> Przeładowałem dane i budynki już się nie pojawiają

Znowu się zawiesiło. 
![image](https://user-images.githubusercontent.com/29873995/101988083-fa2e5200-3c97-11eb-8598-c38680c3ca8e.png)

**Comment by ttomasz** [comment]
Cominutowa aktualizacja jest wstrzymywana na czas cotygodniowej aktualizacji:
![image](https://user-images.githubusercontent.com/31594210/101988682-6f4f5680-3c9b-11eb-8124-cc2e4268ca8e.png)

Może jakoś inaczej to powinno być nazwane, żeby nie było wątpliwości, że jest zależność, ale w sumie nie mam pomysłu jak.

**Comment by CharlesMaZ** [comment]
Aaa, rozumiem. Tylko szkoda, że tak długo trwa ta aktualizacja danych PRG
