### ISSUE TITLE
Niewłaściwie przypisana ulica

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#38]
Czasem zdarza się tak jak na obrazku poniżej, czyli do dobrego adresu przypisana jest ulica podobnie brzmiąca.
Tutaj w adresie powinno być "Zygmunta Wróblewskiego", numer, kod pocztowy i współrzędne się zgadzają. Plac Wróblewskiego też jest, ale w innym miejscu i nie ma numeru 5.
Czy te błędy są w PRG czy w aplikacji?

![adres](https://user-images.githubusercontent.com/57260466/101280496-bd5ee880-37c9-11eb-8769-cc8c3e82607e.png)
https://budynki.openstreetmap.org.pl/#map=18.4/51.105478/17.076433

**Comment by ttomasz** [comment]
W PRG jest dobrze ( https://mapy.geoportal.gov.pl/imap/Imgp_2.html?locale=en&gui=new&sessionID=5353171 ). Na którymś etapie czyszczenia się źle dopasowuje, spróbuję znaleźć na którym.

**Comment by maro-21** [comment]
Po ostatniej aktualizacji ten adres ma już dobrze przypisaną ulicę. Wiadomo gdzie był błąd?

**Comment by ttomasz** [comment]
Hm, zmieniłem jeden skrypt przypisujący kody simc i ulic, żeby oddzielnie obsługiwał 5 miast z wydzielonymi dzielnicami/delegaturami w TERYT, ale to jeszcze nie było wgrane na serwer przy ostatniej aktualizacji, więc nie wiem czemu teraz jest dobrze 😅

**Comment by maro-21** [comment]
Coś się popsuło po dzisiejszej aktualizacji. 
We Wrocławiu w polu miejscowość zamiast "Wrocław" pokazuje np. "Wrocław-Fabryczna". Nie wiem skąd to się wzięło. "Fabryczna" to była kiedyś dzielnica Wrocławia, ale dzielnic nie ma już od 30 lat.

Nie wiem czy błąd był już w zeszłą sobotę, tego nie widziałem, bo wtedy nie doszły żadne nowe adresy.

Możesz wydzielić ten post do osobnego tematu jeśli trzeba, ale wydaje mi się, że jest on związany z tamtą zmianą.

**Comment by ttomasz** [comment]
W TERYT dalej są dzielnice i nienawidzę tego jak GUS to pogmatwał...

Masz rację, że to związane ze zmianą którą robiłem tutaj. Dla kodu SIMC dorobiłem warunek, że jeżeli miasto należy do tych pięciu nieszczęsnych miast z dzielnicami/delegaturami to biorę kod SIMC wpisany w PRG (a tam podają kod całego miasta) zamiast ten z TERYT, ale zapomniałem, że z nazwą tak samo powinienem robić.

Dzięki za czujność. Poprawię i przeładuję dane.
