### ISSUE TITLE
opracowanie mapowań z kategorii budynków BDOT na tagi OSM

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/gugik2osm#40]
Jak będziemy przełączać źródło budynków z loda1 na bdot to warto by było skorzystać z atrybutów tam zawartych.
Atrybuty to m. in. liczba_kondygnacji, zabytek (true/false), nazwa oraz kategoria budynku. Kategorie i przykładowe nazwy załączone jako pliki tekstowe.

**Comment by ttomasz** [comment]
[bdot_nazwy.txt](https://github.com/openstreetmap-polska/gugik2osm/files/5685081/bdot_nazwy.txt)
[bdot_funkcje.txt](https://github.com/openstreetmap-polska/gugik2osm/files/5685082/bdot_funkcje.txt)

**Comment by maro-21** [comment]
Jeśli chodzi o funkcje, to widzę że to będzie dużo roboty z tym, jeśli chcemy znaleźć odpowiedniki tagów OSM.

Jeśli chodzi o nazwy - naprawdę jest to w danych urzędowych?
Nie wiem czy będą przydatne, bo po 5 minutach znalazłem tyle:
- `Sanktuarium Najświętrzej Maryi Panny Pocieszenia` - błąd ortograficzny
- `m` - ?
- `Młyn` - nazwa pospolita
- `McDonald's Polska Sp. z o.o.` - tak nie wpisujemy w OSM
- `NOWOŚĆ`
- `459/5` - wygląda jak numer działki
- `Szkoła Podstawowa nr 9` - zwykle dajemy na teren, więc nie będzie to nazwa budynku
- `Gimnazjum im. Czesława Niemena` - jeszcze jakieś gimnazja są...

**Comment by ttomasz** [comment]
No są, chociaż jakość jak widać :) ale może ktoś będzie miał pomysł, czy coś z tego wyciągnąć można.
Generalnie geopackage z tym co mam dostępne jest do pobrania z https://budynki.openstreetmap.org.pl/opis_danych.html można sobie w qgis otworzyć jakieś województwo.
A ogólnie dobry opis struktury BDOT jest tutaj: http://www.wodgik.katowice.pl/www/pobierz/VADEMECUM_UZYTKOWNIKA_BDOT10k.pdf
W tej chwili mam tylko przetworzoną warstwę BUBD.

**Comment by wzbartczak** [comment]
Z pliku bdot_funkcje coś się zrobi i z ilością pracy bym nie przesadzał, bałagan jest niezły. Mam nawet pomysł jak się do tego zabrać.  Poproszę tylko trochę czasu. Słownik się napiszę ;-)

**Comment by ttomasz** [comment]
zapiszę link do mapowań tutaj też żeby było w jednym miejscu: https://docs.google.com/spreadsheets/d/1IAd6T0t2xVLRpEi9ZTMSmYD2qKk-n4SJTBSZSSeXQmc/
