### ISSUE TITLE
Serwer nie wstaje sam po restarcie

### ISSUE THREAD

**Issue by jendrusk** [openstreetmap-polska/gugik2osm#42]
Do sprawdzenia - wygląda jakby nginx próbował wstać zbyt wcześnie i po restarcie hosta nie wstaje...

**Comment by ttomasz** [comment]
prawdopodobnie chodzi o to, że katalog ```/run/``` jest czyszczony przy restarcie, tam jest plik ```/run/gugik2osm/osmhelper.sock``` którego gunicorn i nginx używają do komunikacji

**Comment by ttomasz** [comment]
ręcznie naprawiałem komendami: 
```bash
sudo mkdir /run/gugik2osm/
touch /run/gugik2osm/osmhelper.sock
```

**Comment by ttomasz** [comment]
```/run``` jest zamontowany pod tmpfs który jest w ramie i jeszcze czyszczony przy restarcie, zmienię ścieżkę, żeby nie było tego katalogu który jest właściwie zbędny, wtedy powinien być w stanie sobie utworzyć ten socket bez ingerencji człowieka i wtać poprawnie po restarcie

**Comment by ttomasz** [comment]
jednak to nie takie proste...

**Comment by olo81** [comment]
może doinstalowanie "monit" coś pomoże
domoticz na raspaberry też nie chciał mi wstawać i monit rozwiązał problemy 

https://mmonit.com/monit/

**Comment by ttomasz** [comment]
chyba naprawione
