### ISSUE TITLE
sprawdzić algorytm porównywania numerów porządkowych kiedy numery mają spację

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/gugik2osm#43]
https://budynki.openstreetmap.org.pl/#map=17.94/54.00959/20.071139

**Comment by maro-21** [comment]
To chyba dobrze teraz działa. Nie powinno być spacji w numerach.

**Comment by ttomasz** [comment]
![image](https://user-images.githubusercontent.com/31594210/102393433-a2198780-3fd8-11eb-94ff-5fa28d40ed76.png)
to jest problem, nie powinno pokazywać adresów jako brakujących jeżeli jest tylko różnica w spacji

**Comment by maro-21** [comment]
Chodziło mi o to, że dobrze że wykrywa, bo można taki adres poprawić;) Ale jeśli jest takie założenie, że tego nie musi robić, to ok :)

**Comment by ttomasz** [comment]
commit: e9e63fc6c383523dc3d4c77d15a1f312cf6d3928 powinien to chyba naprawić
