### ISSUE TITLE
warstwa o eksportach za bardzo przesłania mapę

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#44]
Tak wygląda mapa, gdy tylko pobrałem paczkę z adresami, ale jeszcze ich nie dodałem na OSM.
![adresy](https://user-images.githubusercontent.com/57260466/102700121-f2981b80-424a-11eb-9a5f-57bafac1788d.png)

Po pierwsze chyba za szybko to się wyświetla - ja tylko pobrałem dane, ale ich jeszcze nie wysłałem.
Ta pomarańczowa plansza za bardzo zasłania mapę, a chciałem jeszcze parę rzeczy na tej mapie sprawdzić, jest tam adres, który wymaga przeniesienia w nowe miejsce, a teraz go nie mogę zobaczyć.

**Comment by maro-21** [comment]
A tak to wygląda, gdy już dodałem te adresy:
![adresy2](https://user-images.githubusercontent.com/57260466/102700295-7b638700-424c-11eb-923d-b991823c1e90.png)

Po pierwsze - jeszcze bardziej nic nie widać :P
A po drugie, dziwne, że zawiera też kafle na których nic nie zmieniłem.

Jak rozwiązać ten problem? Może samo obramowanie zamiast wypełnionego prostokąta albo możliwość wyłączenia ich w warstwach.

**Comment by ttomasz** [comment]
> chyba za szybko to się wyświetla
Z założenia miało się możliwie szybko wyświetlać, teraz warstwa aktualizuje się co 60s. Poza tym, że fajnie wygląda to miało być jako też takie dodatkowe zabezpieczenie/podpowiedź dla użytkownika, że ktoś w tym terenie chyba będzie edytować, żeby dwóch użytkowników na raz w jednym rejonie nie wrzuciło danych.

> pomarańczowa plansza za bardzo zasłania mapę
Mogę trochę zwiększyć przezroczystość i tak jak wspominałeś dodać włączanie/wyłączanie w panelu warstw.

> dziwne, że zawiera też kafle na których nic nie zmieniłem.
Hm no tutaj te kafle są dość blisko tych punktów, ciężko stwierdzić "na oko" czy nie zahaczają o jakiś punkt.

**Comment by ttomasz** [comment]
Zwiększyłem trochę przezroczystość oraz dodałem do panelu opcję włączania i wyłączania warstw:
![image](https://user-images.githubusercontent.com/31594210/103478511-947d4380-4dc7-11eb-9945-7f9ceb68459f.png)
![image](https://user-images.githubusercontent.com/31594210/103478525-a363f600-4dc7-11eb-9563-e539b4047e68.png)

**Comment by maro-21** [comment]
Super, dzięki!
