### ISSUE TITLE
brak adresów w woj. dolnośląskim

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#47]
Nie ma adresów tylko na Dolnym Śląsku. Co się stało?
![dolnoslaskie](https://user-images.githubusercontent.com/57260466/109399942-32b00480-7946-11eb-9a8b-04ccaa41a0a4.png)

Nie, nie dodaliśmy wszystkich adresów w międzyczasie ;)

**Comment by ttomasz** [comment]
Kurczę miałem jakieś złe ustawienia githuba i maile mi nie przychodziły. Plik od dolnośląskiego się źle pobrał :( Nie sprawdzę teraz czy GUGiK zły wystawił (co zdarzało się w przeszłości) czy coś po prostu przerwało losowo transfer, ale kolejna aktualizacja w piątek sama powinna naprawić.
