### ISSUE TITLE
adresy blisko siebie

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#47]
W miejscu strzałki powinien być adres 17, jednak aplikacja nie sugeruje jego dodania. Czy to dlatego, że jest bardzo blisko 19a?
![adresy](https://user-images.githubusercontent.com/57260466/103156144-10630480-47a6-11eb-8d3c-5ec3e5f73e79.png)
![adresy2](https://user-images.githubusercontent.com/57260466/103156145-12c55e80-47a6-11eb-9536-f2b86d4dd8da.png)
https://budynki.openstreetmap.org.pl/#map=19/51.1448524/17.2219941

**Comment by ttomasz** [comment]
Jest warunek, że jeżeli dla danego adresu PRG jest jakikolwiek adres w OSM w odległości bodajże do 5m to nie będzie on pokazywany. Można tę odległość dopasować, bo może te 5 metrów to za dużo.

**Comment by ttomasz** [comment]
Może zmniejszyć to do 2 metrów żeby wykluczyć punkty które są praktycznie w tym samym miejscu?

**Comment by maro-21** [comment]
> Jest warunek, że jeżeli dla danego adresu PRG jest jakikolwiek adres w OSM w odległości bodajże do 5m to nie będzie on pokazywany. Można tę odległość dopasować, bo może te 5 metrów to za dużo.

A nie może po prostu sprawdzać to czy TEN SAM adres, a nie jakikolwiek? ;)

**Comment by ttomasz** [comment]
No niestety to nie jest takie łatwe :D Mogą być różnice w sposobie zapisu ulicy, numeru porządkowego, lokalizacji.

**Comment by ttomasz** [comment]
zmieniłem limit na 2 metry i zobaczymy jak wyjdzie, powinno pokazywać więcej takich punktów jak na obrazku

**Comment by ttomasz** [comment]
Sprawdziłem ten link i po zmianie pokazuje ten punkt z numerem 17 więc chyba jest ok.

**Comment by maro-21** [comment]
Te 2 metry to nie jest tak naprawdę rzeczywista odległość, a na pewno nie zawsze, jeśli aplikacja działa tak jak pisałeś wcześniej, że w przypadku adresu na budynku bierze odległość od jego środka ciężkości. Czasami adresy mogą być dodane przez kogoś ręcznie i wtedy punkt nie będzie dokładnie w tym samym miejscu co w PRG. Pewnie w rzeczywistości adresy reprezentujące wejścia do klatki budynku nie będą w odległości mniejszej niż 1,5 m, bo tyle to szerokość drzwi. Piszę to dlatego, że spokojnie można zmniejszyć nawet do jednego metra:)

Poniższy obrazek trochę rozjaśnia, to co napisałem wyżej
![adresy](https://user-images.githubusercontent.com/57260466/105238401-e0244100-5b6c-11eb-90bf-6e23eada5def.png)


![adresy2](https://user-images.githubusercontent.com/57260466/105238462-e4e8f500-5b6c-11eb-9c59-3ff43930214d.png) Tu dobry przykład na niepotrzebne łączenie adresu z budynkiem... adres ten nie został wykryty przez odległość 5 metrów ustawioną wcześniej.

![adresy3](https://user-images.githubusercontent.com/57260466/105238582-ec100300-5b6c-11eb-939e-ec32a718464a.png)
Tutaj adresy się zmieniły z 5-6 na 5 oraz z 7-8 na 7. Aplikacja wykryła tylko jeden, bo w przypadku drugiego budynku ta odległość była mniejsza niż 2 metry.
