### ISSUE TITLE
Nowa ortofotomapa

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#48]
Nowy WMS z nową ortofotomapą z Geoportalu jest już dostępny.
Wystarczy podmienić początek adresu z 
`https://mapy.geoportal.gov.pl/wss/service/img/guest/ORTO/MapServer/WMSServer`
na `https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/StandardResolution`

https://www.geoportal.gov.pl/o-geoportalu/aktualnosci/-/asset_publisher/HCHq0YGNRszn/content/15-02-2021-nowe-uslugi-wms-i-wmts-dla-ortofotomapy

**Comment by ttomasz** [comment]
Dzięki! Dodane.
