### ISSUE TITLE
zaznaczono 0 adresów

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/gugik2osm#5]
oryginalny issue stworzony przez maro-21

**Comment by ttomasz** [comment]
![image](https://user-images.githubusercontent.com/31594210/105559898-b4db5680-5d12-11eb-87d4-e54777d7ff49.png)

**Comment by maro-21** [comment]
Czemu stare repozytorium zostało usunięte i nowe stworzone "ręcznie"? Teraz nie mogę śledzić postępów moich zgłoszonych problemów, nie będę mógł też odpowiedzieć na ewentualne pytanie. Przecież można przenieść repo z zachowaniem historii.

**Comment by ttomasz** [comment]
@maro-21 Niestety koledze się omsknął palec i usunął poprzednie repo, a możliwości przywracania usuniętego repo na github są mocno ograniczone. W związku z tym odtworzyłem co się dało tutaj.

**Comment by ttomasz** [comment]
fixed in 248eb26ec5de9dab2a7e84a53a6dc7cfdd8380fe
