### ISSUE TITLE
dodać link do OSM.org

### ISSUE THREAD

**Issue by maro-21** [openstreetmap-polska/gugik2osm#53]
Dobrze by było dodać gdzieś link do OSM. Często potrzebuję się przenieść na stronę OSM, żeby znaleźć obiekt z adresem, który wymaga poprawy.
Można to łatwo zrobić, bo zarówno w adresie budynki.osm.org.pl jak i na stronie głównej jest ta sama końcówka:
https://budynki.openstreetmap.org.pl/#map=14/51.6225/18.68806
         https://www.openstreetmap.org/#map=14/51.6225/18.68806

**Comment by ttomasz** [comment]
Póki pamiętam, linki do ikonek możliwych do wykorzystania. 
https://fontawesome.com/icons/globe-europe?style=solid
https://fontawesome.com/icons/map-marked-alt?style=solid
https://fontawesome.com/icons/map-signs?style=solid

**Comment by maro-21** [comment]
Albo można po prostu wykorzystać logo OSM
https://wiki.openstreetmap.org/wiki/File:Public-images-osm_logo.svg
https://wiki.openstreetmap.org/wiki/File:Public-images-osm_logo.png

**Comment by ttomasz** [comment]
Dodane

**Comment by maro-21** [comment]
Dzięki :)
