### ISSUE TITLE
Zablokować dostęp bez logowania, dać dostęp tylko wybranym osobom

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/gugik2osm#58]
Niestety, kolejni importują na ślepo

**Comment by ttomasz** [comment]
Jeżeli dostęp mieliby mieć tylko wybrani namaszczeni to równie dobrze stronę można zamknąć. 

Taki urok, że jak projekt (OSM) robi się duży i coraz więcej ludzi edytuje to będzie coraz więcej błędów. Trzeba raczej zastanowić się jak takie sytuacje możliwie szybko wykrywać. Np bot który liczy ile było edycji na terenie polski i jeżeli jakiś użytkownik w krótkim czasie dokonuje gigantycznych edycji (liczba obiektów w przedziale czasowym) to automatycznie daje mu lekkiego bana i info jak się skontaktować ze stowarzyszeniem w celu wyjaśnienia sytuacji.

**Comment by matkoniecz** [comment]
Hmm, może #57 wystarczy.
