### ISSUE TITLE
Przygotowanie pod testy serwera kafelków live

### ISSUE THREAD

**Issue by jendrusk** [openstreetmap-polska/gugik2osm#6]
WHAT
Kafelki z rozbieżnościami między OSM a LOD i PRG powinny być wyświetlane na stronie.

WHY
Jako że idziemy w kierunku aktualizowanych danych generowanie pliku .mbtiles zacznie być upierdliwe... trzeba znaleźć inne rozwiązanie 

HOW
Trzeba przygotować mini-serwer kafli wektorowych na podstawie danych z bazy. Zadanie dość proste - endpoint flaska najlepiej jako oddzielna aplikacja uruchamiana oddzielnym gunicornem w wielu wątkach. Cały endpoint ma za zadanie tylko przekonwertować otrzymany zestaw z/x/y do współrzędnych (np. mercantile) i złożyć odpowiednie zapytanie do bazy. Baza danych wygeneruje odpowiedni kafelek, a endpoint ma za zadanie jedynie przekierować go na front.

Zadanie było już ćwiczone wcześniej przez @ttomasz nie mniej wyniki wydajnościowe nie były zadowalające - trzeba się pochylić nad tematem, dołożyć indeksy przestrzenne i popracowac nad wydajnością. Jeśli rozwiązanie zda egzamin będzie dołączone do projektu, jeśli nie wylatuje.

**Comment by jendrusk** [comment]
Zrobiłem szybkie testy na bazie do której zaimportowałem wszystkie budynki w Polsce. Zapytanie nie szły dłużej niż 200ms dla kafelka zl 13, i na poziomie 10-25ms dla kafelków ZL >=15, więc chyba warto to napisać... Plik z testowymi zapytaniami:
[test.zip](https://github.com/openstreetmap-polska/gugik2osm/files/3957985/test.zip)

**Comment by jendrusk** [comment]
Rozwijane w ramach gałęzi ak_mvt_srv

**Comment by ttomasz** [comment]
Obecnie kafelki mają 3 warstwy:
- lod1_buildings - obrysy budynków, były generowano od zoom 14 do 19 ale można ten zakres zwiększyć np. od 12 bo jeszcze powinny być widoczne na tym zoom level
- prg2load_geomonly - punkty adresowe sama geometria, były przerzedzane automatycznie przez narzędzie którym generowałem kafelki tippecanoe (od mapbox) od zoom 6 do bodajże 15, nie wiem czy to przerzedzanie w postgisie da się zrobić czy nie
- prg2load - punkty adresowe, poza geometrią atrybuty ze wszystkimi wartościami co w sumie było trochę bez sensu, proponuję zostawić 'lokalnyid' i 'nr' i dodać w aplikacji endpoint do pobierania info dla punktu o danym punkcie po 'lokalnyid' ( a nr potrzebny do wyświetlania na mapie) - dla tej warstwy nie było żadnego usuwania punktów, widoczna od zoom 15 do 19

Nazwy warstw można jakoś pozamieniać, tylko trzeba będzie pamiętać żeby potem zmienić w web/map.js

**Comment by ttomasz** [comment]
Dodano
