### ISSUE TITLE
Błędy w lokalizacji adresów 

### ISSUE THREAD

**Issue by Arnebius** [openstreetmap-polska/gugik2osm#62]
Nastąpił błąd co do lokalizacji adresów w ramach importów z PRG, obecnie na stronie https://budynki.openstreetmap.org.pl/ w przykładowej lokalizacji np. Bystrzyca Kłodzka mamy adresy z miejscowości Jawor oddalonej o kilkadziesiąt kilometrów.

**Comment by ttomasz** [comment]
Dzięki za zwrócenie uwagi. Robiłem aktualizację serwera i najwyraźniej PostGIS 3.0 inaczej czyta GML niż PostGIS 2.4 :) Przeładuję dane i powinno być ok.

**Comment by ttomasz** [comment]
naprawiane w commit 3ad3dbe2dcda6440424571dd150ee0af18cf15de
