### ISSUE TITLE
dane do woj. małopolskiego (błąd)

### ISSUE THREAD

**Issue by qlachtar** [openstreetmap-polska/gugik2osm#68]
hej,
Pod linkiem do danych do woj. małopolskiego znajdują się dane do woj.lubuskiego. Tutaj: 

https://budynki.openstreetmap.org.pl/opis_danych.html?fbclid=IwAR3-4EGivHv51TJXmt3AKf9711VqJ7cvECQ8Qu1jIo2ft7SGtJxvUDOPkNA

Czy byłoby możliwe dla Was wstawienie danych do małopolski? Bylbym super wdzięczny. Btw dzięki wielkie za udostępnenie projektu - nie muszę sklejać danych dla powiatów :))).
Pozdawiam

**Comment by ttomasz** [comment]
Dzięki za zwrócenie uwagi, poprawię linki w weekend i napiszę tu jak będzie ok 🙂

**Comment by ttomasz** [comment]
Poprawiłem. Możliwe, że trzeba odświeżyć za pomocą ctrl+f5 żeby przeglądarka wywaliła cache.

**Comment by qlachtar** [comment]
Super dzięki; podziele się jak stworzę coś na podstawie tych map - pracuję nad opracowaniem urbanistycznym Górnego Śląska
