### ISSUE TITLE
Budynki w budowie

### ISSUE THREAD

**Issue by maraf24** [openstreetmap-polska/gugik2osm#86]
Aktualnie budynki w budowie są importowane jako zbudowane.
Proponuję je oznaczać jako building=construction, ew. pomijać.

![image](https://user-images.githubusercontent.com/10471006/132632867-aa2f447e-7865-4e42-a977-c9a0128ef4f0.png)
![image](https://user-images.githubusercontent.com/10471006/132632969-38a05635-9b59-4729-9e0e-98617c809c70.png)

**Comment by ttomasz** [comment]
Dodałem regułę żeby building był jako construction kiedy status w bdot jest jako "w budowie". W sobotę po aktualizacji powinno być widoczne.

Swoją drogą tak przedstawia się liczba per status wszystkich budynków z warstwy BUBD w BDOT10k:

gugik2osm=> select status_bdot, count(*) from bdot_buildings_all group by 1 ;
  status_bdot  |  count
---------------+----------
 eksploatowany | 14888259
 w budowie     |   155931
(2 rows)
