### ISSUE TITLE
podanie źródła coś się chowa - coś ze stylem jest nie tak?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/gugik2osm#90]
https://budynki.openstreetmap.org.pl/#map=17.46/50.17382/21.025476

![screen09](https://user-images.githubusercontent.com/899988/135732528-a5224c47-d8f2-4ac4-bad0-072cd40d7508.png)

**Comment by ttomasz** [comment]
@Ancymonek to chyba przez te zmiany żeby nie było białego paska co kiedyś robiłeś? 😅

**Comment by Ancymonek** [comment]
> 
> 
> @Ancymonek to chyba przez te zmiany żeby nie było białego paska co kiedyś robiłeś? 😅

Tak, to pewnie przez tę wartość procentową height. No nic, przyjrzę się temu

**Comment by Ancymonek** [comment]
@ttomasz 
Znalazłem "brudny" hack - można dodać do klasy .mapboxgl-ctrl-bottom-right wartość position: fixed !important. Atrybucja będzie wtedy zawsze w prawym dolnym rogu. Minus jest taki, że jak ktoś sobie zmniejszy ekran do malutkich rozdzielczości to atrybucja będzie nachodziła na inne elementy.

**Comment by ttomasz** [comment]
Dodane
